### ISSUE TITLE
mcap 0.0.18 failed to read messages

### ISSUE THREAD

**Issue by chenrui333** [foxglove/mcap#581] opened 2022-09-14 22:14 UTC
**Description**

Trying to install 0.0.18, but failed to cat the message

- Version: mcap cli 0.0.18
- Platform: macOS
- go version: 1.19.1

**Steps To Reproduce**
- Install latest mcap cli, `go install github.com/foxglove/mcap/go/cli/mcap@latest`
- run `cat OneMessage-ch-chx-mx-pad-rch-rsh-st-sum.mcap | xxx/golang/1.19.1/packages/bin/mcap cat`
- get the error outout

```
2022/09/14 17:25:51 Failed to read messages: end cannot come before start
```

**Expected Behavior**

`Expected: "2 example [Example] [1 2 3]"`

**Actual Behavior**

```
2022/09/14 17:25:51 Failed to read messages: end cannot come before start
```

---

relates to https://github.com/Homebrew/homebrew-core/pull/110694

**Comment by jtbandes** [comment] 2022-09-14 22:54
Duplicate of #580 
@chenrui333 Was there a reason you filed two issues for this one? Not sure if these issues are automated or filed manually. Thanks for reporting them!

**Closed by jtbandes** 2022-09-14 22:54 UTC
Labels: bug
