### ISSUE TITLE
File missing on build for TS library in Deno

### ISSUE THREAD

**Issue by jcpsimmons** [foxglove/mcap#1039] opened 2023-12-08 20:57 UTC
**Description**

protobufjs.d.ts needs to be moved into typescript folder for build.

<img width="1262" alt="Screenshot 2023-12-08 at 1 54 15 PM" src="https://github.com/foxglove/mcap/assets/6600962/5811c8dd-de3d-46ee-a26e-b876a5c096b7">

- Version: 1.0.0
- Platform: TypeScript - `@mcap/support` library

**Steps To Reproduce**

1. Initialize a Deno project
2. Add `@mcap/support` as a dependency
3. Run `deno compile`

**Expected Behavior**

For the application to compile.

**Comment by defunctzombie** [comment] 2023-12-09 00:14
There's been no work to test or support deno - we've only published npm packages for use with node.js or browser-like bundlers. We'd be open to reviewing and considering contributions to support deno (assuming they don't break other systems) but have no plans to do this ourselves as of now.

I am gonna close this as not planned because its not a bug since we've not claimed to support deno.

**Closed by defunctzombie** 2023-12-09 00:14 UTC
Labels: bug
